remote_theme: pages-themes/minimal@v0.2.0
title: J. Yim
description: Skilled written and verbal communicator across varied audiences and environments of diverse age, cultural, and technical backgrounds.

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
