remote_theme: pages-themes/minimal@v0.2.0
title: testing title location
description: testing description location

mainfont: "Times New Roman"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
